### PR TITLE
Support pipenv

### PR DESCRIPTION
**Pull request by NathanYocum**
This PR switches the primary development tool to pipenv over virtual envs - since it makes dependency management easier and easier to trace with static analysis.

This will also make development tools like flake8, black, pylint, etc. much easier to set up for local developers to get to PEP8 coding standards.

### CODE REVIEW

**Comment by loganjohnlong** [comment]
Failing check is OK, ignore for now.

**Comment by loganjohnlong** [comment]
Looks good to me, as this should not affect the production environment.

**Comment by NathanYocum** [comment]
Alright I'll leave merging to you since you have more familiarity with Azure @loganjohnlong

**Comment by loganjohnlong** [comment]
Working in a production environment

**Pull request merged**
